---
name: Semantic Release

permissions:
    id-token: write
    contents: write

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        concurrency: release

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Python Semantic Release
              uses: python-semantic-release/python-semantic-release@v8.0.0
              with:
                  github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  # repository_username: __token__
                  # repository_password: ${{ secrets.PYPI_TOKEN }}
